TRIPHASE_VERSION                    = 913
MATLAB_ROOT_TGT                     = /home/triphase/MATLAB/R2016b
USER_SRCS                           = 
USER_INCLUDES                       = 
S_FUNCTIONS                         = rtiostream_utils.c tc0.c
S_FUNCTIONS_LIBS                    = 
SHARED_LIB                          = 
EXT_SHARED_LIB                      = 
DEFAULT_OPT_OPTS                    = 
TGT_FCN_LIB                         = GNU
NON_ANSI_TRIG_FCN                   = 
DO_GCC_TEST                         = 
GCC_WARN_OPTS_MAX                   = 
GCC_TEST                            = 
WARN_ON_GLNX                        = 
SHARED_SRC                          = 
SHARED_BIN_DIR                      = 
SHARED_SRC_DIR                      = 
MODEL                               = PM15A30I60F06_afAC3_vsAC3_csDC1
USERNAME_LOWERCASE                  = triphase
DAYS_TO_PRESERVE_LOG                = 2
CONTINUOUS_LOGS                     = 
STOP_LOGS                           = 
MODULES                             = PM15A30I60F06_afAC3_vsAC3_csDC1_data.c event_logger.c rtBuffer.c rtGetInf.c rtGetNaN.c rt_nonfinite.c rt_zcfcn.c 
SOLVER                              = 
BASE_PRIORITY                       = 60
RT_STACK_SIZE                       = 0
DOUBLE_BUFFER_PARAMETERS            = 0
STOPONOVERRUN                       = 1
INSTRUMENT_INCLUDES                 = 
INSTRUMENT_LIBS                     = 
EXT_MODE                            = 1
EXTMODE_STATIC                      = 0
EXTMODE_STATIC_SIZE                 = 1000000
TP_EXT_MODE                         = 0
TP_EXT_MODE_LIGHT                   = 1
FLOAT_MATH_MODE                     = SSE
TP_MATH                             = 1
TP_METRICS                          = 0
AUTO_TASK_TO_CORE_MAPPING           = 0 
TASK_TO_CORE_MAPPING                = 2 3
AUTO_EXTMODE_TASK_TO_CORE_MAPPING   = 0 
EXTMODE_TASK_TO_CORE_MAPPING        = 3
EXTRA_MODEL_CONFIG_FILE             = toolbox_config.conf
CIPC_CONFIG_FILE                    = PM15A30I60F06_afAC3_vsAC3_csDC1_config
CIPC_PACKED                         = 0
TP_AMESIM_ROOT                      = 
TP_AMESIM_SUBMODELS                 = 
TP_RTW_S_FUNCTIONS                  = 
EXTERNAL_MODE_PORT                  = 17735
COMPUTER                            = PCWIN64
RELEASE_VERSION_SHORT               = R2016b
OPT_OPTS                            = 
CPP_OPTS                            = 
LD_OPTS                             = 
OPTS                                = -DON_TARGET_WAIT_FOR_START=0
CODE_FORMAT                         = RealTime
ENABLE_TIMER                        = 0
NUMST                               = 5
TID01EQ                             = 1
NCSTATES                            = 0
MODELLIB                            = PM15A30I60F06_afAC3_vsAC3_csDC1lib.lib
MODELREF_LINK_LIBS                  = 
MODELREF_INC_PATH                   = 
MODELREF_TARGET_TYPE                = NONE
PRECOMP_LIBS                        = 
REGULAR_LIBS                        = 


