TRIPHASE_VERSION         = 912
MATLAB_ROOT_TGT          = /home/triphase/MATLAB/R2012b
USER_SRCS                = 
USER_INCLUDES            = 
S_FUNCTIONS              = 
S_FUNCTIONS_LIBS         = 
SHARED_LIB               = 
EXT_SHARED_LIB           = 
DEFAULT_OPT_OPTS         = 
TGT_FCN_LIB              = GNU
NON_ANSI_TRIG_FCN        = 
DO_GCC_TEST              = 
GCC_WARN_OPTS_MAX        = 
GCC_TEST                 = 
WARN_ON_GLNX             = 
SHARED_SRC               = 
SHARED_BIN_DIR           = 
SHARED_SRC_DIR           = 
MODEL                    = AFE_SIM
USERNAME_LOWERCASE       = piet
DAYS_TO_PRESERVE_LOG     = 2
CONTINUOUS_LOGS          = 
STOP_LOGS                = 
MODULES                  = AFE_SIM_data.c rtGetInf.c rtGetNaN.c rt_nonfinite.c rt_zcfcn.c 
SOLVER                   = 
BASE_PRIORITY            = 60
RT_STACK_SIZE            = 0
MULTITASKING             = 1
KEEP_TET_INFO            = 1
DOUBLE_BUFFER_PARAMETERS = 0
STOPONOVERRUN            = 1
INSTRUMENT_INCLUDES      = 
INSTRUMENT_LIBS          = 
EXT_MODE                 = 1
EXTMODE_STATIC           = 0
EXTMODE_STATIC_SIZE      = 1000000
TP_EXT_MODE              = 0
TP_EXT_MODE_LIGHT        = 1
TP_AMESIM_ROOT           = 
TP_AMESIM_SUBMODELS      = 
TP_RTW_S_FUNCTIONS       = 
EXTERNAL_MODE_PORT       = 17725
COMPUTER                 = GLNX86
RELEASE_VERSION_SHORT    = R2012b
OPT_OPTS                 = -mtune=native -DTASK_0_AFF=1 -DTASK_1_AFF=1 -DTASK_2_AFF=1 -DTASK_3_AFF=1 -DTASK_4_AFF=1 -DTASK_5_AFF=1 -DMAIN_TASK_AFF=1 -DEXT_MODE_AFF=1 -DS_EXT_MODE_AFF=1 -DSIMULINK_BUILD -ffast-math -mfpmath=387 
CPP_OPTS                 = 
LD_OPTS                  = 
OPTS                     = 
CODE_FORMAT              = RealTime
ENABLE_TIMER             = 1
NUMST                    = 4
TID01EQ                  = 1
NCSTATES                 = 28
MODELLIB                 = AFE_SIMlib.lib
MODELREF_LINK_LIBS       = 
MODELREF_INC_PATH        = 
MODELREF_TARGET_TYPE     = NONE
PRECOMP_LIBS             = 
REGULAR_LIBS             = 


