TRIPHASE_VERSION         = 912
MATLAB_ROOT_TGT          = /home/triphase/MATLAB/R2016b
USER_SRCS                = 
USER_INCLUDES            = 
S_FUNCTIONS              = rtiostream_utils.c
S_FUNCTIONS_LIBS         = 
SHARED_LIB               = 
EXT_SHARED_LIB           = 
DEFAULT_OPT_OPTS         = 
TGT_FCN_LIB              = GNU
NON_ANSI_TRIG_FCN        = 
DO_GCC_TEST              = 
GCC_WARN_OPTS_MAX        = 
GCC_TEST                 = 
WARN_ON_GLNX             = 
SHARED_SRC               = 
SHARED_BIN_DIR           = 
SHARED_SRC_DIR           = 
MODEL                    = MEAS_HUB
USERNAME_LOWERCASE       = triphase_setup
DAYS_TO_PRESERVE_LOG     = 2
CONTINUOUS_LOGS          = 
STOP_LOGS                = 
MODULES                  = MEAS_HUB_data.c rtGetInf.c rtGetNaN.c rt_nonfinite.c 
SOLVER                   = 
BASE_PRIORITY            = 60
RT_STACK_SIZE            = 0
MULTITASKING             = 0
KEEP_TET_INFO            = 1
DOUBLE_BUFFER_PARAMETERS = 0
STOPONOVERRUN            = 1
INSTRUMENT_INCLUDES      = 
INSTRUMENT_LIBS          = 
EXT_MODE                 = 1
EXTMODE_STATIC           = 0
EXTMODE_STATIC_SIZE      = 1000000
TP_EXT_MODE              = 0
TP_EXT_MODE_LIGHT        = 0
TP_AMESIM_ROOT           = 
TP_AMESIM_SUBMODELS      = 
TP_RTW_S_FUNCTIONS       = 
EXTERNAL_MODE_PORT       = 17725
COMPUTER                 = GLNX86
RELEASE_VERSION_SHORT    = R2016b
OPT_OPTS                 = -mtune=native
CPP_OPTS                 = 
LD_OPTS                  = 
OPTS                     = -DON_TARGET_WAIT_FOR_START=0
CODE_FORMAT              = RealTime
ENABLE_TIMER             = 1
NUMST                    = 1
TID01EQ                  = 0
NCSTATES                 = 0
MODELLIB                 = MEAS_HUBlib.lib
MODELREF_LINK_LIBS       = 
MODELREF_INC_PATH        = 
MODELREF_TARGET_TYPE     = NONE
PRECOMP_LIBS             = 
REGULAR_LIBS             = 


