#! /bin/sh
# Above line is just used for syntax highlighting in VIM

# Config file for CIPC buffer process

# Outputs

MEAS_APP_port.buffer_name = MEAS_APP_port
MEAS_APP_port.buffer_order = 4


APP_MEAS_port.buffer_name = APP_MEAS_port
APP_MEAS_port.buffer_order = 4
