TRIPHASE_VERSION                    = 913-beta4
MATLAB_ROOT_TGT                     = /home/triphase/MATLAB/R2012b
USER_SRCS                           = 
USER_INCLUDES                       = 
S_FUNCTIONS                         = 
S_FUNCTIONS_LIBS                    = 
SHARED_LIB                          = 
EXT_SHARED_LIB                      = 
DEFAULT_OPT_OPTS                    = 
TGT_FCN_LIB                         = GNU
NON_ANSI_TRIG_FCN                   = 
DO_GCC_TEST                         = 
GCC_WARN_OPTS_MAX                   = 
GCC_TEST                            = 
WARN_ON_GLNX                        = 
SHARED_SRC                          = 
SHARED_BIN_DIR                      = 
SHARED_SRC_DIR                      = 
MODEL                               = MEAS_HUB
USERNAME_LOWERCASE                  = piet
DAYS_TO_PRESERVE_LOG                = 2
CONTINUOUS_LOGS                     = 
STOP_LOGS                           = 
MODULES                             = MEAS_HUB_data.c rtGetInf.c rtGetNaN.c rt_nonfinite.c 
SOLVER                              = 
BASE_PRIORITY                       = 60
RT_STACK_SIZE                       = 0
KEEP_TET_INFO                       = 0
DOUBLE_BUFFER_PARAMETERS            = 0
STOPONOVERRUN                       = 1
INSTRUMENT_INCLUDES                 = 
INSTRUMENT_LIBS                     = 
EXT_MODE                            = 1
EXTMODE_STATIC                      = 0
EXTMODE_STATIC_SIZE                 = 1000000
TP_EXT_MODE                         = 0
TP_EXT_MODE_LIGHT                   = 1
FLOAT_MATH_MODE                     = SSE
TP_MATH                             = 1
AUTO_TASK_TO_CORE_MAPPING           = 0 
TASK_TO_CORE_MAPPING                = 3
AUTO_EXTMODE_TASK_TO_CORE_MAPPING   = 0 
EXTMODE_TASK_TO_CORE_MAPPING        = 3
EXTRA_MODEL_CONFIG_FILE             = toolbox_config.conf
CIPC_CONFIG_FILE                    = MEAS_HUB_config
CIPC_PACKED                         = 0
TP_AMESIM_ROOT                      = 
TP_AMESIM_SUBMODELS                 = 
TP_RTW_S_FUNCTIONS                  = 
EXTERNAL_MODE_PORT                  = 17725
COMPUTER                            = PCWIN64
RELEASE_VERSION_SHORT               = R2012b
OPT_OPTS                            = 
CPP_OPTS                            = 
LD_OPTS                             = 
OPTS                                = 
CODE_FORMAT                         = RealTime
ENABLE_TIMER                        = 0
NUMST                               = 1
TID01EQ                             = 0
NCSTATES                            = 0
MODELLIB                            = MEAS_HUBlib.lib
MODELREF_LINK_LIBS                  = 
MODELREF_INC_PATH                   = 
MODELREF_TARGET_TYPE                = NONE
PRECOMP_LIBS                        = 
REGULAR_LIBS                        = 


